#!/usr/bin/env bash

BASE_DIR="$(cd "$(dirname "$0")"; pwd)" || exit 2

IFS=$'\n'
entrylist=('Go Back')
rawentry="$(find $BASE_DIR/entries -type f)"
for i in $rawentry; do
i=${i##*/}
entrylist+=("$i")
done

hackeruser=fallout_hack

COLUMNS=12

showclk ()
{
    while sleep 1;do tput sc;tput cup 0 $(($(tput cols)-29));date;tput rc;done &
}

#This function is to display the top header in a centred alignment!
display_center(){
    columns="$(tput cols)"
    while IFS= read -r line; do
        printf "%*s\n" $(( (${#line} + columns) / 2)) "$line"
    done < "$1"
}


#This string is to be displayed as a custom "title header" at the top, feel free to customise it, as most Terminals in Fallout have their own custom one based on their owner!
greeter=$'
Personal Terminal "Proto-Boy" Manufactured by RobCo
___________________________________________________'

displaygreeter ()
{
#display the Menu text
play -q $BASE_DIR/ui_hacking_charscroll.wav
display_center "$BASE_DIR/greeterheader.txt" | pv -qL 80
echo "$greeter" | pv -qL 80
play -q $BASE_DIR/ui_hacking_charscroll.wav

}

mainmenupass ()
{

while true
do
    clear
    displaygreeter

    #showclk

    echo -n "Utilisateur : " | pv -qL 80
    read utilisateur
    echo -n "Mot de passe : " | pv -qL 80
    read -s password
    printf "\n"
    getent passwd $utilisateur > /dev/null
    if [ $? -eq 0 ]; then
        origpass=`grep -w "$utilisateur" /etc/shadow | cut -d: -f2`
        algo=`echo $origpass | cut -d'$' -f2`
        salt=`echo $origpass | cut -d'$' -f3`
        
        export password
        export algo
        export salt

        genpass=$(perl -le 'print crypt("$ENV{password}","\$$ENV{algo}\$$ENV{salt}\$")')
        if [ "$genpass" == "$origpass" ]
        then
            echo 'Correct password.'
            read
        else 
            echo 'Wrong password.'
            read
        fi    
            printf "Bonjour, $utilisateur\n"
            displaymainmenu
        else
            printf "L'utilisateur n'existe pas"
            read
        fi
done

}


displaymainmenu()
{
#Display the menu options
COLUMNS=12

select menuchoice in "View Journal Entries for $utilisateur" "Log a Journal Entry" "Delete a Journal Entry" "Logout"
do
    case $menuchoice in
    "View Journal Entries for $utilisateur")
    play -q $BASE_DIR/ui_hacking_charenter_01.wav
    viewentriesfunc
    ;;
    "Log a Journal Entry")
    play -q $BASE_DIR/ui_hacking_charenter_01.wav
    writeentryfunc
    ;;
    "Delete a Journal Entry")
    play -q $BASE_DIR/ui_hacking_charenter_01.wav
    deleteentryfunc
    ;;
    "Logout")
    play -q $BASE_DIR/ui_hacking_charenter_01.wav
    echo Goodbye! && return 9
    ;;
    *)
    play -q $BASE_DIR/ui_hacking_passbad.wav
    ;;
    esac
done
}


#Main Menu Screen
mainmenufunc () 
{
clear

#display the Menu text
displaygreeter
echo What would you like to do? | pv -qL 80

displaymainmenu

}

getentries ()
{
#find entries for user
userdirs=''

#adding all the text files as individual strings to be used as a selection menu
entrynames=('Go Back')
entrydirs=('')
entryusers=('')

##debug
hackeruser="blue1"
##

if [ $utilisateur = $hackeruser ]
then
users=`members blue`
users+=" "
users+=`members red`
IFS=' ' read -a usersarr <<< $users
else
usersarr=($utilisateur)
fi

for user in ${usersarr[@]}
do
  userdir=`getent passwd $user | cut -d":" -f6`
  #This line needs bash 4.4-alpha or better
  readarray -d '' -O "${#entrydirs[@]}" entrydirs < <(find $userdir/fallout_entries/entries -type f -print0)
done

for i in ${entrydirs[@]}
do
    usrdir=`echo $i | cut -f 3 -d /`
    i=${i##*/}
    if [ $utilisateur = $hackeruser ]
    then
        entrynames+=("$i ($usrdir)")
    else
        entrynames+=("$i")
    fi
#    echo -e $i
done
#read
}

#Option 1 Menu, Viewing Journal Entries
viewentriesfunc () 
{
    getentries
#display the Menu text
    clear
    display_center "$BASE_DIR/greeterheader.txt"
    echo "$greeter" 
    play -q $BASE_DIR/ui_hacking_charscroll.wav
    echo Which $utilisateur Journal Entry would you like to access? | pv -qL 80
    
    #display the menu options
    COLUMNS=12
    select readoption in ${entrynames[@]}
    do
    case $readoption in
    "Go Back")
    play -q $BASE_DIR/ui_hacking_charenter_01.wav
    #repeatmainmenufunc
    return
    ;;
        *)
    play -q $BASE_DIR/ui_hacking_charenter_01.wav
    ;;
    esac

    #displays the selected entry
    clear
    display_center "$BASE_DIR/greeterheader.txt"
    echo "$greeter"
    echo
    play -q $BASE_DIR/ui_hacking_charscroll.wav
    echo "$readoption:"  | pv -qL 80
    play -q $BASE_DIR/ui_hacking_charscroll.wav
    #cat< "$BASE_DIR/entries/$readoption"  | pv -qL 80
    
    ##dbg
    #for edd in ${entrydirs[@]}
    #do
    #    echo $edd
    #done
    #for edd in ${!entrydirs[@]}
    #do
    #    echo $edd
    #done
    #for edd in ${entrynames[@]}
    #do
    #    echo $edd
    #done
    #
    #echo "red option : " $readoption
    #read
    ##

    for i in ${!entrynames[@]}
    do
        if [[ "${entrynames[$i]}" = $readoption ]]
        then
            cat< "${entrydirs[$i]}"  | pv -qL 80
        fi
    done
    echo
    read -p "Press enter to continue"
    play -q $BASE_DIR/ui_hacking_charenter_01.wav
    
    #goes back to main menu
    #repeatmainmenufunc
    return 
    done
}

#menu for writing an entry
writeentryfunc () 
{

#displays menu text
clear
displaygreeter
echo "What would you like to name the entry?" | pv -qL 80

#reads user input
read entrynameinput 
play -q $BASE_DIR/ui_hacking_charenter_01.wav

#displays menu text again
clear
display_center "$BASE_DIR/greeterheader.txt"
echo "$greeter" 
play -q $BASE_DIR/ui_hacking_charscroll.wav
echo Press CTRL+D to finalise entry  | pv -qL 80
play -q $BASE_DIR/ui_hacking_charscroll.wav
echo $entrynameinput:  | pv -qL 80
echo
#uses cat text editor to write entries. ctrl+d to finish
cat >"$BASE_DIR/entries/$entrynameinput"
cat "$BASE_DIR/entries/$entrynameinput"
clear
play -q $BASE_DIR/ui_hacking_charenter_01.wav

#returns to mainmenu
#repeatmainmenufunc
return


}

#menu to delete an entry
deleteentryfunc () 
{

#adding all the text files as individual strings to be used as a selection menu
entrylist=('Go Back')
rawentry="$(find $BASE_DIR/entries -type f)"
for i in $rawentry; do
i=${i##*/}
entrylist+=("$i")
done

    #displays menu text
    clear
    display_center "$BASE_DIR/greeterheader.txt"
    echo "$greeter" 
    play -q $BASE_DIR/ui_hacking_charscroll.wav
    echo Which Journal Entry would you like to delete? | pv -qL 80
    
    #displays menu options
    COLUMNS=12
    select readoption in ${entrylist[@]}
    do
    case $readoption in
    "Go Back")
    play -q $BASE_DIR/ui_hacking_charenter_01.wav
    #repeatmainmenufunc
    return
    ;;
        *)
    play -q $BASE_DIR/ui_hacking_charenter_01.wav
    ;;
    esac
    
    #displays menu text again
    clear
    display_center "$BASE_DIR/greeterheader.txt"
    echo "$greeter"
    echo
    play -q $BASE_DIR/ui_hacking_charscroll.wav
    echo "Delete $readoption? Type YES to continue"  | pv -qL 80
    play -q $BASE_DIR/ui_hacking_charscroll.wav
    
    #detects user input if they typed in "yes". case insensitive as it converts it to all caps
    read confirmdeletion
     if  [[ ${confirmdeletion^^} == "YES" ]]
     then
        rm -f "$BASE_DIR/entries/$readoption"
        play -q $BASE_DIR/ui_hacking_charenter_01.wav
        echo FILE DELETED!
        play -q  $BASE_DIR/ui_hacking_passgood.wav
        sleep 0.1
        #repeatmainmenufunc
        return
                
            #if something other than yes was typed in
    else
        echo OPERATION CANCELLED
        play -q $BASE_DIR/ui_hacking_charenter_01.wav
        play -q  $BASE_DIR/ui_hacking_passbad.wav
        sleep 0.2
        
        #goes back to main menu
        #repeatmainmenufunc
        return
    fi
    done
}

#same as main menu screen function, but without the annoying animations
repeatmainmenufunc ()
{

while true
do
    clear

    display_center "$BASE_DIR/greeterheader.txt"
    echo "$greeter" 
    play -q $BASE_DIR/ui_hacking_charscroll.wav
    echo What would you like to do? | pv -qL 80

    ret=displaymainmenu
    if [ ret == 9 ]
    then
        return 9
    fi
done
}

startupscreen ()
{
    #some random aesthetic startup junk

    clear
    play -q $BASE_DIR/ui_hacking_charscroll.wav
    echo Initializing boot... | pv -qL 80
    sleep 0.4
    play -q $BASE_DIR/ui_hacking_charscroll.wav
    echo Loading RobCo Unified OS...  | pv -qL 80
    sleep 0.4
    play -q $BASE_DIR/ui_hacking_charscroll.wav
    echo 64K RAM detected...  | pv -qL 80
    sleep 0.4
    play -q $BASE_DIR/ui_hacking_charscroll.wav
    echo Launching Interface...  | pv -qL 80
    sleep 0.4
    clear
    echo $'


      _____       _      _____                   
     |  __ \     | |    / ____|                  
     | |__) |___ | |__ | |     ___               
     |  _  // _ \| \'_ \| |    / _ \              
     | | \ \ (_) | |_) | |___| (_) |             
     |_|__\_\___/|_.__/ \_____\___/  _           

    '

    echo "==============================================" | pv -qL 50
    play -q $BASE_DIR/ui_hacking_passgood.wav
    sleep 1

}

#startupscreen;

#goes to the main menu
mainmenupass;
